// ADD USERS
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_LOADING = "ADD_USER_LOADING";
export const ADD_USER_ERROR = "ADD_USER_ERROR";
// GET USERS
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_LOADING = "GET_USERS_LOADING";
export const GET_USERS_ERROR = "GET_USERS_ERROR";
// MODIFY USERS
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_LOADING = "EDIT_USER_LOADING";
export const EDIT_USER_ERROR = "EDIT_USER_ERROR";
// DELETE USERS
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_LOADING = "DELETE_USER_LOADING";
export const DELETE_USER_ERROR = "DELETE_USER_ERROR";